# From https://github.com/cachedout/barnacle
FROM cent7:latest

# Copy files
COPY files/gitconfig /root/

# Ensure we're in the homedir when the container launches
WORKDIR /root

# Ensure a UTF-8 locale
ENV LANG en_US.UTF-8
